export const URLS = {
  BASE: '.',
  POSTS: '/api/posts',
  HOME_HERO: '/api/home-hero',
  HOME_PRIMARY_FEATURES: '/api/home-primary-feature',
  HOME_SECONDARY_FEATURES: '/api/home-secondary-feature',
  HOME_CTA: '/api/home-cta',
  HOME_TESTMONIALS: '/api/home-testimonial',
  HOME_FAQ: '/api/home-faq',
  HOME_PRICING: '/api/home-pricing',
  UPLOAD_IMAGE: '/api/media/upload-image',
  CATEGORY: '/api/categories',
  ABOUT_US: '/api/about-us',
  CONTACT: '/api/contact',
  // ABOUT_US_COMMITMENT: '/api/about-us-commitment',
  // ABOUT_US_DEVELOPMENT: '/api/about-us-development',
  // ABOUT_US_MISSION: '/api/about-us-mission',
  // ABOUT_US_VALUE: '/api/about-us-value',
};

export const QUERY_KEYS = {
  ALL_POSTS: 'ALL_POSTS',
  POST_BY_ID: 'POST_BY_ID',
  HOME_HERO: 'HOME_HERO',
  HOME_PRIMARY_FEATURES: 'HOME_PRIMARY_FEATURES',
  HOME_SECONDARY_FEATURES: 'HOME_SECONDARY_FEATURES',
  HOME_CTA: 'HOME_CTA',
  HOME_TESTMONIALS: 'HOME_TESTMONIALS',
  HOME_FAQ: 'HOME_FAQ',
  HOME_PRICING: 'HOME_PRICING',
  CATEGORY: 'CATEGORY',
  ABOUT_US: 'ABOUT_US',
  CONTACT: 'CONTACT',
  // ABOUT_US_COMMITMENT: 'ABOUT_US_COMMITMENT',
  // ABOUT_US_DEVELOPMENT: 'ABOUT_US_DEVELOPMENT',
  // ABOUT_US_MISSION: 'ABOUT_US_MISSION',
  // ABOUT_US_VALUE: 'ABOUT_US_VALUE',
};
